version: "3"

services:
  node:
    build: .
    user: node
    container_name: xp-desafio
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - database
    ports:
      - 3000:3000
    environment:
      - API_PORT=3000
      - NODE_ENV=development
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - HOSTNAME=database
      - JWT_SECRET=minhaSenhaSecreta
  database:
    container_name: xp-desafio-bd
    image: mysql:8.0.29
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - dados-do-banco:/var/lib/mysql

networks:
  default:

volumes:
  dados-do-banco: